---
- name: user module demo
  hosts: ap01
  #become: true
  vars:
    myuser: "demo"
    mypassword: "password"
  tasks:
    - name: Remove the user
      ansible.builtin.user:
        name: example
        state: absent
        remove: yes
